# Generated by Django 3.0.2 on 2020-02-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Timeslot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='listing',
        ),
    ]
